on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

    inputs:
      dummyparam:
        description: 'enter a string'
        type: string   
        required: true
        

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"

  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.inputs.dummyparam }}"